
# config
appName: "main"
version: "1.0.0"
clientType: "PC_WEB"
title: "microFrontend-1"
serverPort: 6000
logLevel: "INFO"
logDist: "d:\\log/main"
# bff keep-alive超时时间
# keepAliveTimeout: 60000
# backend socket超时时间
socketTimeout: 60000
# 文件处理超时时间
fileSocketTimeout: 180000
# 加密编码
encoding: "base64"

# dev
## client
dev_clientPort: 4000
dev_publicPath: '/'
dev_apiPath: "https://www.fastmock.site/mock/0a0043432a43fb517e7bb068685f2114/testapi"
## server
dev_domainUrl: "http://paludina.dev.com"
dev_backendUrl: "https://focusapi.vemic.com/mock/209"

# prod
## client
publicPath: "/dist/"
apiPath: "https://focusapi.vemic.com/mock/209"
## server
domainUrl: "https://paludina.prod.com"
backendUrl: "https://focusapi.vemic.com/mock/209"

# 微应用
microApps: ['form', 'table']

# 依赖的包
dependencyPackages: ['lcdp-rc']

# cdn 地址
cdn: ""
